### ISSUE TITLE
Error for Authorization code flow in example

### ISSUE THREAD

**Issue by hansentaurus** [Mendeley/mendeley-javascript-sdk#16]
Hi, I tried to run the example to check authorization code flow.
But it causes error.
In index.html, the apiAuthenticateUrl is set as '/logout'. Is this correct one?
And though I change it to '/login', I still get error of "Cannot call method 'authorizeURL' of undefined" in oauth-app.js:33.
Please let me why such error occured and what do I have to do to fix that.
Regards. Johanne.

**Comment by customcommander** [comment]
Hi,

I didn't have any issues running the example. Have you registered the "app" on http://dev.mendeley.com/ and put the generated client ID in the configuration?

![sdk_examples](https://cloud.githubusercontent.com/assets/681975/7862890/c5dfb2ca-0550-11e5-8ebb-fb295aeb8a28.png)

**Comment by hansentaurus** [comment]
I found the problem in my code. I forgot to close this issue. Sorry for that.
Btw, great plugin!
